### PR TITLE
Refactor code to make changes easier

### PR DESCRIPTION
**Pull request by pajachiet**
I tried to make commit history simple.

This refactor should not modify existing behaviors

### CODE REVIEW

**Review by AntoineAugusti — APPROVED** [review]
Thanks for submitting a PR! How are you going to use these new changes?

I ran Black (https://github.com/ambv/black) before merging the PR

**Comment by AntoineAugusti** [comment]
I released a version 0.3 with these changes https://github.com/AntoineAugusti/table-schema-to-markdown/commit/1baac4efc703b93f15ea9e5624a3fecce9b694ff

**Comment by pajachiet** [comment]
Thanks a lot.
We need some evolutions to generate markdown from schemas generated in this [repository](https://github.com/indsante/schema-snds)

These changes will make them easier :)

**Comment by AntoineAugusti** [comment]
Can you send me a commit / link to a PR when you'll use these changes? I'm curious

**Comment by pajachiet** [comment]
Yes, obviously. There are not many yet.

I already introduced a behaviour for "name" property to use as main header in this PR.

The last commit on this branch decrease headers level https://github.com/pajachiet/table-schema-to-markdown/commits/change-format-for-documentation-snds. 
As it changed the current behavior I did not included it in this PR.

Next work will be to render foreign keys.

**Pull request merged**
